import express from "express";
import authRoute from "./auth.route";
import serviceRoute from "./service.route";
import bookingRoute from "./booking.route";
import cartRoute from "./cart.route";
import notificationRoute from "./notification.route";
import userRoute from "./user.route";
import paymentRoute from "./payment.route";
import blogRoute from "./blog.route";
import petRoute from "./pet.route";
import supportRoute from "./support.route";
import vipRoute from "./vip.route";
import invoiceRoute from "./invoice.route";
import productRoute from "./product.route";
import { authorized } from "../middleware/auth.middleware";
import productCategoryRoute from "./product_category.route";
import serviceCategoryRoute from "./service_category.route";
import staffRoute from "./staff.route";
import reviewRoute from "./review.route";
import appointmentRoute from "./appointment.route";
import commissiontRoute from "./commission.route";
import contactHistoryRoute from "./contact_history.route";
import serviceReviewRoute from "./service_review.route";
import reportRoute from "./report.route";
import inventoryRoutes from "./inventory.route";
import ratingRoutes from "./rating.route";
import adminRoute from "./admin/dashboard.route";
import orderRoute from "./order.route";
import supplierRoute from "./order.route";
import orderPaymentRoute from "./order_payment.route";
import chatRoute from './chat_message.route';
import servicePaymentRoute from "./service_payment.route";

import { apiLimiter } from "../utils/rateLimit";

const router = express.Router();

// router.use(apiLimiter);
router.use("/auth", authRoute);
router.use("/users", userRoute);
router.use("/chat", chatRoute);
router.use("/suppliers", supplierRoute);
router.use("/orders", orderRoute);
router.use("/staff", staffRoute);
router.use("/ratings", ratingRoutes);
router.use("/inventory", inventoryRoutes);
router.use("/reports", reportRoute);
router.use("/order-payment", orderPaymentRoute);
router.use("/service-payment", servicePaymentRoute);
router.use("/reviews", reviewRoute);
router.use("/service-reviews", serviceReviewRoute);
router.use("/contact-histories", contactHistoryRoute);
router.use("/product-category",productCategoryRoute);
router.use("/product", productRoute);
router.use("/commissions", commissiontRoute);
router.use("/cart",cartRoute);
router.use("/service-category", serviceCategoryRoute);
router.use("/services", serviceRoute);
router.use("/appointments", appointmentRoute);
router.use("/booking", bookingRoute);
router.use("/payments", paymentRoute);
router.use("/notifications", notificationRoute);
router.use("/pets", petRoute);
router.use("/blogs", blogRoute);
router.use("/support", supportRoute);
router.use("/vip", vipRoute);
router.use("/invoice", invoiceRoute);
router.use("/admin", adminRoute);
export default router;
